# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

project_name: Tmuxinator
project_root: ~/Code/Rails
tabs:
  - main:
      layout: dee0,238x59,0,0{159x59,0,0,0,78x59,160,0[78x29,160,0,3,78x29,160,30,4]}
      panes:
        - vim .
        - 
  - console:
      layout: main-horizontal
      pains:
        - zeus console
  - server:
      layout: main-horizontal
      panes:
        - zeus server
