# ~/.tmuxinator/default.yml

project_name: Tmuxinator
project_root: ~/Code
windows:
  - main:
      layout: a118,208x53,0,0{139x53,0,0,9,68x53,140,0[68x36,140,0,10,68x16,140,37,11]}
      panes:
        - 
        -
